import { assert } from "chai";
import { getNrOfMoves } from "./b.js";

describe("23-b Unstable Diffusion", () => {
  const input = 
`..............
..............
.......#......
.....###.#....
...#...#.#....
....#...##....
...#.###......
...##.#.##....
....#..#......
..............
..............
..............`;
    it("should return 20", () => {
    const result = getNrOfMoves(input);
    assert.equal(result, 20);
  });
});
